const dotenv = require('dotenv')
dotenv.config({ path: `${process.cwd()}/.env` })

const API_PORT = process.env.API_PORT
const API_HOST = process.env.API_HOST
const API_PATH = process.env.API_PATH
const DEVELOP_MODE = process.env.DEVELOP_MODE
const API_UPLOAD_PATH = process.env.API_UPLOAD_PATH
const API_UPLOAD_INCLUDE_PATHS = process.env.API_UPLOAD_INCLUDE_PATHS
const AUTH_DB_DATABASE_NAME = process.env.AUTH_DB_DATABASE_NAME
const AUTH_DB_DATABASE_HOST = process.env.AUTH_DB_DATABASE_HOST
const AUTH_DB_DATABASE_PORT = process.env.AUTH_DB_DATABASE_PORT
const AUTH_DB_DATABASE_USERNAME = process.env.AUTH_DB_DATABASE_USERNAME
const AUTH_DB_DATABASE_PASSWORD = process.env.AUTH_DB_DATABASE_PASSWORD
const AUTH_DB_DATABASE_AUTO_CREATE = process.env.AUTH_DB_DATABASE_AUTO_CREATE
const AUTH_DB_MONGODB_URI = process.env.AUTH_DB_MONGODB_URI
const AUTH_DB_DATABASE_REPLICA_SET = process.env.AUTH_DB_DATABASE_REPLICA_SET
const API_FILE_FIELDS = process.env.API_FILE_FIELDS
const SESSION_TOKEN_DEFAULT_TIME = process.env.SESSION_TOKEN_DEFAULT_TIME
const REFRESH_TOKEN_DEFAULT_TIME = process.env.REFRESH_TOKEN_DEFAULT_TIME
const RESET_TOKEN_DEFAULT_TIME = process.env.RESET_TOKEN_DEFAULT_TIME
const RESEND_TOKEN = process.env.RESEND_TOKEN
const RESEND_API_URL = process.env.RESEND_API_URL
const ADMIN_MAIL_FROM = process.env.ADMIN_MAIL_FROM
const BRAND_PRIMARY_COLOR = process.env.BRAND_PRIMARY_COLOR
const BRAND_ACCENT_COLOR = process.env.BRAND_ACCENT_COLOR
const BRAND_URL = process.env.BRAND_URL
const BRAND_EMAIL_LANGUAGE = process.env.BRAND_EMAIL_LANGUAGE
const PASSWORD_RESET_URL_BASE = process.env.PASSWORD_RESET_URL_BASE
const PASSWORD_RESET_ALLOWED_URL_BASES = process.env.PASSWORD_RESET_ALLOWED_URL_BASES
const CHANGE_PASSWORD_CODE_DEFAULT_TIME = process.env.CHANGE_PASSWORD_CODE_DEFAULT_TIME
const CHANGE_PASSWORD_CODE_MAX_ATTEMPTS = process.env.CHANGE_PASSWORD_CODE_MAX_ATTEMPTS
const METRICS_ROUTE = process.env.METRICS_ROUTE
const METRICS_PREFIX = process.env.METRICS_PREFIX
const CORS_ALLOWED_ORIGINS = process.env.CORS_ALLOWED_ORIGINS
const METRICS_TOKEN = process.env.METRICS_TOKEN
const RATE_LIMIT_WINDOW_MS = process.env.RATE_LIMIT_WINDOW_MS
const RATE_LIMIT_MAX = process.env.RATE_LIMIT_MAX
const RATE_LIMIT_STRICT_WINDOW_MS = process.env.RATE_LIMIT_STRICT_WINDOW_MS
const RATE_LIMIT_STRICT_MAX = process.env.RATE_LIMIT_STRICT_MAX
const SECURITY_CORP_POLICY = process.env.SECURITY_CORP_POLICY
const CONFIRMATION_CODE_DEFAULT_TIME = process.env.CONFIRMATION_CODE_DEFAULT_TIME
const CONFIRMATION_CODE_MAX_ATTEMPTS = process.env.CONFIRMATION_CODE_MAX_ATTEMPTS
const CONFIRMATION_CODE_RESEND_COOLDOWN = process.env.CONFIRMATION_CODE_RESEND_COOLDOWN
const LOGIN_RECORD_MAX_PER_EMAIL = process.env.LOGIN_RECORD_MAX_PER_EMAIL
const LOGIN_RECORD_TTL = process.env.LOGIN_RECORD_TTL
const UNCONFIRMED_ACCOUNT_TTL = process.env.UNCONFIRMED_ACCOUNT_TTL
const BRAND_NAME = process.env.BRAND_NAME
const BRAND_LOGO_URL = process.env.BRAND_LOGO_URL

module.exports = {
	API_PORT,
	API_HOST,
	API_PATH,
	DEVELOP_MODE,
	API_UPLOAD_PATH,
	API_UPLOAD_INCLUDE_PATHS,
	AUTH_DB_DATABASE_NAME,
	AUTH_DB_DATABASE_HOST,
	AUTH_DB_DATABASE_PORT,
	AUTH_DB_DATABASE_USERNAME,
	AUTH_DB_DATABASE_PASSWORD,
	AUTH_DB_DATABASE_AUTO_CREATE,
	AUTH_DB_MONGODB_URI,
	AUTH_DB_DATABASE_REPLICA_SET,
	API_FILE_FIELDS,
	SESSION_TOKEN_DEFAULT_TIME,
	REFRESH_TOKEN_DEFAULT_TIME,
	RESET_TOKEN_DEFAULT_TIME,
	RESEND_TOKEN,
	RESEND_API_URL,
	ADMIN_MAIL_FROM,
	BRAND_PRIMARY_COLOR,
	BRAND_ACCENT_COLOR,
	BRAND_URL,
	BRAND_EMAIL_LANGUAGE,
	PASSWORD_RESET_URL_BASE,
	PASSWORD_RESET_ALLOWED_URL_BASES,
	CHANGE_PASSWORD_CODE_DEFAULT_TIME,
	CHANGE_PASSWORD_CODE_MAX_ATTEMPTS,
	METRICS_ROUTE,
	METRICS_PREFIX,
	CORS_ALLOWED_ORIGINS,
	METRICS_TOKEN,
	RATE_LIMIT_WINDOW_MS,
	RATE_LIMIT_MAX,
	RATE_LIMIT_STRICT_WINDOW_MS,
	RATE_LIMIT_STRICT_MAX,
	SECURITY_CORP_POLICY,
	CONFIRMATION_CODE_DEFAULT_TIME,
	CONFIRMATION_CODE_MAX_ATTEMPTS,
	CONFIRMATION_CODE_RESEND_COOLDOWN,
	LOGIN_RECORD_MAX_PER_EMAIL,
	LOGIN_RECORD_TTL,
	UNCONFIRMED_ACCOUNT_TTL,
	BRAND_NAME,
	BRAND_LOGO_URL
}