const dotenv = require('dotenv')
dotenv.config({ path: `${process.cwd()}/.env` })

const API_PORT = process.env.API_PORT
const API_HOST = process.env.API_HOST
const API_PATH = process.env.API_PATH
const DEVELOP_MODE = process.env.DEVELOP_MODE
const API_UPLOAD_PATH = process.env.API_UPLOAD_PATH
const API_UPLOAD_INCLUDE_PATHS = process.env.API_UPLOAD_INCLUDE_PATHS
const AUTH_DB_DATABASE_NAME = process.env.AUTH_DB_DATABASE_NAME
const AUTH_DB_DATABASE_HOST = process.env.AUTH_DB_DATABASE_HOST
const AUTH_DB_DATABASE_PORT = process.env.AUTH_DB_DATABASE_PORT
const AUTH_DB_DATABASE_USERNAME = process.env.AUTH_DB_DATABASE_USERNAME
const AUTH_DB_DATABASE_PASSWORD = process.env.AUTH_DB_DATABASE_PASSWORD
const AUTH_DB_DATABASE_AUTO_CREATE = process.env.AUTH_DB_DATABASE_AUTO_CREATE
const AUTH_DB_MONGODB_URI = process.env.AUTH_DB_MONGODB_URI
const AUTH_DB_DATABASE_REPLICA_SET = process.env.AUTH_DB_DATABASE_REPLICA_SET
const API_FILE_FIELDS = process.env.API_FILE_FIELDS

module.exports = {
	API_PORT,
	API_HOST,
	API_PATH,
	DEVELOP_MODE,
	API_UPLOAD_PATH,
	API_UPLOAD_INCLUDE_PATHS,
	AUTH_DB_DATABASE_NAME,
	AUTH_DB_DATABASE_HOST,
	AUTH_DB_DATABASE_PORT,
	AUTH_DB_DATABASE_USERNAME,
	AUTH_DB_DATABASE_PASSWORD,
	AUTH_DB_DATABASE_AUTO_CREATE,
	AUTH_DB_MONGODB_URI,
	AUTH_DB_DATABASE_REPLICA_SET,
	API_FILE_FIELDS
}